package by.javatr.personalfinance.controller.command;

public enum CommandName {

    REGISTER,
    SING_IN,
    SING_OUT,
    UPDATE_USER_DATA,
    DELETE_USER,

    BAN,
    UNBAN,

    ADD_ACCOUNT,
    GET_ACCOUNT,
    GET_ACCOUNT_LIST,
    GET_BALANCE,
    GET_COMMON_BALANCE,
    UPDATE_ACCOUNT,
    DELETE_ACCOUNT,

    ADD_TRANSACTION,
    GET_TRANSACTION,
    GET_TRANSACTION_LIST,
    UPDATE_TRANSACTION,
    DELETE_TRANSACTION,

    WRONG_REQUEST
}